### ISSUE TITLE
Plans for Linq2db release 2.0

### ISSUE THREAD

**Issue by sdanyliv** [LinqToDB4iSeries/Linq2DB4iSeries#9]
@RoyC-Retail-Assist, do you have plans to upgrade provider?
We have request for supporting iSeries in LINQPad and it is not possible if your source code is not up to date.

Thanks.

**Comment by RoyC-Retail-Assist** [comment]
I am planning to check that there aren't any breaking changes in the next few days.  I'd like to get the unit tests refreshed to match the current tests in Linq2DB but that is going to take longer and may reveal some bits of the provider that need addressing.

I'd like to work out some way of getting this rolled back into being a native provider somehow so that any advances in the unit tests could automatically apply to it but I'm not sure how we would go about this.  Can we discuss this some time when everyone is less busy?

**Comment by RoyC-Retail-Assist** [comment]
Apart from a minor PR to LinqToDb code, I have a working version compatible with 2.0.0-rc2 that passes all tests.  I anticipate committing a working release a few days after LinqToDb 2 is released.

**Comment by RoyC-Retail-Assist** [comment]
v2.2.0.3 released and package on NuGet

**Comment by travbeamo** [comment]
Version 3 is out now, do you plan to update this excellent repository?

https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0
